notifications:
  email: false

env:
  global:
  - GHC_OPTIONS="-O0 -Werror"
  - PACKCHECK="./packcheck.sh"
  # The commit id of packcheck.sh to use from harendra-kumar/packcheck on github
  - PACKCHECK_COMMIT="182d8767120600dee57432ea85d8c847e2a86d09"

# This matrix has total 11 builds enabled, 4 builds each (3 last major compiler
# versions and head) for stack and cabal, 2 OSX builds (stack and cabal for
# latest compiler version), and one hlint build. You may want to comment out
# some of the builds to be lighter on the CI infrastructure.
#
# We pre-install the cabal-install package to not incur the penalty of building
# it the first time in cached builds or every time in uncached builds.
matrix:
  include:

  # --------------------------------------------------------------------------
  # (Linux) stack builds
  # --------------------------------------------------------------------------

  # GHC 7.10.3
  - env: BUILD=stack RESOLVER=lts-6.35
    addons: {apt: {packages: [cabal-install-1.22], sources: [hvr-ghc]}}

  # GHC 8.0.2
  - env: BUILD=stack RESOLVER=lts-9.20
    addons: {apt: {packages: [cabal-install-1.24], sources: [hvr-ghc]}}

  # GHC 8.2.2
  - env: BUILD=stack RESOLVER=lts-10.0
    addons: {apt: {packages: [cabal-install-2.0], sources: [hvr-ghc]}}

  # Nightly
  - env: BUILD=stack RESOLVER=nightly

  # Using a custom stack-yaml config file.
  #- env: BUILD=stack STACK_YAML=.ci/stack-8.0.yaml

  # You can customize the build even without a custom stack-yaml
  # using STACK_OPTIONS, STACK_BUILD_OPTIONS, GHC_OPTIONS etc.
  #- env: BUILD=stack RESOLVER=lts-10.0 STACK_BUILD_OPTIONS="--flag packcheck:dev"

  # --------------------------------------------------------------------------
  # (Linux) cabal builds require pre-installed cabal-install and ghc
  # --------------------------------------------------------------------------

  - env: BUILD=cabal GHCVER=7.10.3 CABALVER=1.22
    addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=8.0.2 CABALVER=1.24
    addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=8.2.2 CABALVER=2.0
    addons: {apt: {packages: [cabal-install-2.0,ghc-8.2.2], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=head CABALVER=head
    addons: {apt: {packages: [cabal-install-head,ghc-head], sources: [hvr-ghc]}}

  # --------------------------------------------------------------------------
  # OS X builds
  # --------------------------------------------------------------------------

  # GHC 8.2.2/cabal build via stack
  - env: BUILD=cabal RESOLVER=lts-10.0
    os: osx

  # GHC 8.2.2/stack
  - env: BUILD=stack RESOLVER=lts-10.0
    os: osx

  # --------------------------------------------------------------------------
  # Lint
  # --------------------------------------------------------------------------

  - env: BUILD=stack RESOLVER=lts-10.0 HLINT_OPTIONS="."

  # --------------------------------------------------------------------------
  # Build and send coverage report to coveralls.io using hpc-coveralls
  # --------------------------------------------------------------------------

  # Note COVERALLS (hpc-coveralls) works only with cabal build.
  # For this to succeed you have to add your porject to coveralls.io first
  #- env: BUILD=cabal GHCVER=8.2.2 CABALVER=2.0 COVERALLS_OPTIONS="--coverage-mode=StrictlyFullLines --exclude-dir=test test"
  #  addons: {apt: {packages: [cabal-install-2.0,ghc-8.2.2], sources: [hvr-ghc]}}

  # --------------------------------------------------------------------------
  # Builds that are allowed to fail
  # --------------------------------------------------------------------------

  allow_failures:
  - env: BUILD=stack RESOLVER=nightly
  - env: BUILD=cabal GHCVER=head CABALVER=head
  - env: BUILD=stack RESOLVER=lts-10.0 HLINT_OPTIONS="."

# ------------------------------------------------------------------------
#  Settings beyond this point are advanced and normally not tweaked
# ------------------------------------------------------------------------

sudo: false
cache:
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
  - $HOME/.local
  - $HOME/.stack

script:
  - |
    # Where to find the packcheck.sh script
    PACKCHECK_URL=https://raw.githubusercontent.com/harendra-kumar/packcheck/${PACKCHECK_COMMIT}/packcheck.sh

    # When GHCVER or CABALVER env variables are specified, modify the path to
    # find the binaries installed from hvr-ghc repo
    add_path()  { eval "test -n \"\$$1\"" && eval "PATH=/opt/$2/\"\$$1\"/bin:$PATH"; true; }

    # Emit the value of the var specified as arg only when the build is cabal
    cabal_env() { test "$BUILD" = cabal && echo $1; }

    CURL=$(which curl)
    PATH=/bin:/usr/bin
    add_path GHCVER   ghc
    add_path CABALVER cabal

    # If a custom stack-yaml is specified, replace the default with that
    if test -e "$STACK_YAML"; then rm -f stack.yaml && ln -sv $STACK_YAML stack.yaml; else true; fi
    if test ! -e "$PACKCHECK"; then $CURL -sL -o "$PACKCHECK" $PACKCHECK_URL; fi;
    chmod +x $PACKCHECK

    # We start with a clean environment (env -i) and specify all the
    # environment variables explicitly. TRAVIS vars are needed by
    # hpc-coveralls.
    # STACK_UPGRADE=y
  - env -i
      LC_ALL=C.UTF-8
      TRAVIS=$TRAVIS
      TRAVIS_JOB_ID=$TRAVIS_JOB_ID
      PATH="$PATH"
      RESOLVER=$RESOLVER
      STACK_BUILD_OPTIONS="$STACK_BUILD_OPTIONS"
      GHCVER=$GHCVER
      GHC_OPTIONS="$GHC_OPTIONS"
      COVERALLS_OPTIONS="$COVERALLS_OPTIONS"
      CABAL_REINIT_CONFIG=y
      TEST_INSTALL=y
      $(cabal_env CABALVER=$CABALVER)
      $(cabal_env CABAL_CHECK_RELAX=y)
      $(cabal_env CABAL_NO_SANDBOX=y)
      $(cabal_env CABAL_HACKAGE_MIRROR=hackage.haskell.org:http://hackage.fpcomplete.com)
      HLINT_OPTIONS="$HLINT_OPTIONS"
      bash -c "$PACKCHECK $BUILD"

install: true
language: c
