environment:
  global:
    RESOLVER: "lts-10.0"
    GHC_OPTIONS: "-O0 -Werror"
    PACKCHECK: packcheck.sh
    # Use the test script without committing it to the repo
    # Specify the commit id in the harendra-kumar/packcheck github repo
    PACKCHECK_COMMIT: "1a4de26422ee296f0811e032bec922123f019963"

    # ------------------------------------------------------------------------
    # Normally you do not need to customize hereafter
    # ------------------------------------------------------------------------

    STACK_ROOT: "c:\\sr"
    LOCAL_BIN: "%APPDATA%\\local\\bin"
    PATH: "%PATH%;%APPDATA%\\local\\bin"
    CABAL_REINIT_CONFIG: "y"
    TEST_INSTALL: "y"

cache:
  - "%STACK_ROOT%"
  - "%LOCAL_BIN%"
  - "%APPDATA%\\cabal"
  - "%APPDATA%\\ghc"
# - "%LOCALAPPDATA%\\Programs\\stack"

clone_folder: "c:\\pkg"
build: off

before_test:
- if not exist %PACKCHECK% curl -sSkL -o%PACKCHECK% https://raw.githubusercontent.com/harendra-kumar/packcheck/%PACKCHECK_COMMIT%/packcheck.sh
- if not exist %LOCAL_BIN% mkdir %LOCAL_BIN%
- where stack.exe || curl -sSkL -ostack.zip http://www.stackage.org/stack/windows-x86_64 && 7z x stack.zip stack.exe && move stack.exe %LOCAL_BIN%
- stack upgrade
- stack --version

test_script:
- stack setup > nul
- chcp 65001 && stack exec bash -c "%PACKCHECK% stack"
